AWSTemplateFormatVersion: "2010-09-09"

Description: An exercise template

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  TiinaPreferredInstanceType:
    Type: String
    Default: 't3.nano'

Outputs:
  LoadBalancerDNSName:
    Description: The DNSName of the TiinanALB load balancer
    Value: !GetAtt TiinanALB.DNSName

Resources:
  TiinanSanko:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tiina-cfbucket
  TiinanJono:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: tiinan-jono
      MessageRetentionPeriod: 300
  TiinanKone:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: !Ref TiinaPreferredInstanceType
      ImageId: !Ref LatestAmiId
      SecurityGroups: 
      - !Ref EC2SecurityGroup
  TiinanALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: TiinanCFALB
      Scheme: internet-facing
      Subnets: 
        - subnet-13a2bf48
        - subnet-66975700
      Tags: 
        - Key: "tiinaCFALB"
          Value: "tiinaCFALBvalue"
      Type: application
      SecurityGroups:
      - !Ref ALBSecurityGroup
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "SG for EC2"
      GroupName: TiinaEC2securityGroupCF
      Tags: 
        - Key: "EC2secGroup"
          Value: "EC2SG"
      SecurityGroupIngress: 
        - FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup
          IpProtocol: TCP
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "SG for ALB"
      GroupName: TiinaALBsecurityGroupCF
      Tags: 
        - Key: "ALBsecGroup"
          Value: "ALBSG"
      VpcId: vpc-2957464e
  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: HTTP
      Name: ALBtargetgroupCF
      Port: 80
      Protocol: HTTP
      Tags: 
        - Key: "ALBTG"
          Value: "ALBTG"
      Targets:
          - Id: !Ref TiinanKone
            Port: 80
      TargetType: instance
      VpcId: vpc-2957464e
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions: 
        - TargetGroupArn: !Ref ALBTargetGroup
          Type: forward
      LoadBalancerArn: !Ref TiinanALB
      Port: 80
      Protocol: HTTP
